---
- hosts: all
  gather_facts: True
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
    ansible_ssh_common_args: -o StrictHostKeyChecking=no


  tasks:
    - name: Write head of file
      lineinfile:
        path: cdp_neigh_list.txt
        line: 'switch,port,remote_host,remote_platform,remote_port'
        insertafter: EOF
        create: yes

    - name: Loop over the dictionary
      lineinfile:
        path: cdp_neigh_list.txt
        line: '{{ inventory_hostname }},{{ item.key }},{{ item.value[0].host }},{{ item.value[0].platform }},{{ item.value[0].port }}'
        insertafter: EOF
        create: yes
      with_dict: "{{ ansible_facts.net_neighbors }}"
