---
# create_ap_list.yaml
# This playbook will capture facts from cisco devices
# and write devicename and port and cdp results to textfile.

- hosts: all
  gather_facts: True
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
    ansible_ssh_common_args: -o StrictHostKeyChecking=no


  tasks:
    - name: Loop over the dictionary
      lineinfile:
        path: aps_list.txt
        line: '{{ inventory_hostname }} - {{ item.key }} - {{ item.value }}'
        insertafter: EOF
        create: yes
      with_dict: "{{ ansible_facts.net_neighbors }}"
      when: '"AIR-" in item.value[0].platform'
