---

# Disable power of AP interface and reenable power to reset the Accesspoint

- hosts: all
  gather_facts: True
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

  tasks:
  
  - name: Disable power of AP interface
    ios_config:
      lines:
        - power inline never
      parents: 'interface {{ item.key }}'
    with_dict: "{{ ansible_facts.net_neighbors }}"
    when: '"AIR-" in item.value[0].platform'

  - name: Enable power of AP interface
    ios_config:
      lines:
        - no power inline never
      parents: 'interface {{ item.key }}'
    with_dict: "{{ ansible_facts.net_neighbors }}"
    when: '"AIR-" in item.value[0].platform'

 
