---
- hosts: all
  gather_facts: False
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
    ansible_ssh_common_args: -o StrictHostKeyChecking=no


  tasks:
    - name: Configure NTP and SYSLOG
      ios_config:
        lines:
          - ntp server 10.1.1.1
          - clock timezone gmt 0
          - clock summer-time BST recurring last Sun Mar 1:00 last Sun Oct 2:00
          - logging host 10.1.1.2
        save_when: modified
        provider: "{{ cli }}"
