---

# Store ansible facts to file to work eg. with python scripts on that
# eg. in python script 
# --
# import json
# with open('facts/switch1.json', 'r') as f:
#     facts = json.loads(f.read())
# --
# Now in facts all facts from ansible are loaded

- hosts: all
  gather_facts: True
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"

  tasks:
    - name: Create facts folder if not exist ...
      file:
        path: "facts"
        state: directory

    - name: Store to facts folder
      copy:
        content: "{{ ansible_facts }}"
        dest: "facts/{{ inventory_hostname }}.json"
        force: yes
